CREATE DATABASE IF NOT EXISTS test;
USE test;
CREATE TABLE IF NOT EXISTS todo (id INTEGER NOT NULL AUTO_INCREMENT, content VARCHAR(200) NOT NULL, date_created DATETIME, PRIMARY KEY (id));
DESCRIBE todo;
